Feature/hit the api
emmyobonyo/leaderboard pull request #2
Opened 2021-09-09 20:17 UTC by emmyobonyo

## Tasks worked on.
- GET API implemented in the REFRESH button.
- POST API implemented.

2021-09-09 20:54 UTC, ZawadiSumba66 requested changes
### Hi @emmyobonyo 👋 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-09 20:54 UTC, ZawadiSumba66 commented on src/index.js
> +
- [ ] Kindly use an arrow function which is a modern syntax provided by the ES6 feature that will make your code look better and neater.

2021-09-09 20:54 UTC, ZawadiSumba66 commented on src/index.js
> +const form = document.getElementById('form');
- [ ] Lets make our code neater by removing commented code form the code base

2021-09-09 20:54 UTC, ZawadiSumba66 commented on README.md
>  ## Run Project
- [ ] Kindly include the `npm install` command to install the dependencies before the `npm start`

2021-09-10 07:44 UTC, emmyobonyo commented on src/index.js
> +const form = document.getElementById('form');
-Comments Removed

2021-09-10 07:45 UTC, emmyobonyo commented on README.md
>  ## Run Project
-```npm install``` added

2021-09-10 07:51 UTC, emmyobonyo commented on src/index.js
> +
-After some consultation, the code being referred to was different from the one above, which I've managed to work on.

2021-09-10 08:12 UTC, ZawadiSumba66 approved these changes
Hi @emmyobonyo again, 
### STATUS: APPROVED 👍 
Great job implementing the changes requested. 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-10 10:20 UTC, merged